# Generated by Django 4.1.1 on 2022-09-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ForCreators', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
                ('Website', models.URLField(null=True)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAnswer', models.CharField(max_length=5)),
                ('Quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ForCreators.quiz')),
                ('enduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForUsers.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='CertificteEraned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificteImg', models.ImageField(upload_to='User Certificte')),
                ('isNFT', models.BooleanField(default=False)),
                ('certificte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForCreators.tempcertificte')),
                ('enduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForUsers.enduser')),
            ],
        ),
    ]
