# Generated by Django 4.1.1 on 2022-09-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('ForCreators', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAnswer', models.CharField(max_length=5)),
                ('Quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ForCreators.quiz')),
                ('enduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
